# Generated by Django 5.2.17 on 2026-09-03 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='sku_loyverse',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
