# Generated by Django 5.2.17 on 2026-09-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('NOUVELLE_COMMANDE', 'Nouvelle commande'), ('COMMANDE_PRETE', 'Commande prête')], max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('target_role', models.CharField(blank=True, choices=[('PREPARATEUR', 'Préparateur'), ('LIVREUR', 'Livreur')], max_length=20, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
