# Generated by Django 6.0.4 on 2026-09-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_sale_sold_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='movement',
        ),
        migrations.RemoveField(
            model_name='product',
            name='magasin',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='magasin',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='magasin',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seller',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='commande_role',
            field=models.CharField(blank=True, choices=[('PREPARATEUR', 'Préparateur'), ('LIVREUR', 'Livreur')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('order', 'Commande'), ('supplier_order', 'Commande fournisseur'), ('user', 'User'), ('chat', 'Chat'), ('caisse', 'Caisse'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.DeleteModel(
            name='Movement',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
