# Generated by Django 6.0.4 on 2026-09-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_remove_notification_movement_remove_product_magasin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos/'),
        ),
    ]
