# Generated by Django 6.0.4 on 2026-09-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_customuser_adresse_customuser_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformrequest',
            name='device',
        ),
        migrations.RemoveField(
            model_name='platformrequest',
            name='admin_profile',
        ),
        migrations.RemoveField(
            model_name='platformrequest',
            name='login_event',
        ),
        migrations.RemoveField(
            model_name='platformrequest',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='platformrequest',
            name='requested_by',
        ),
        migrations.RemoveField(
            model_name='platformrequest',
            name='resolved_by',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='admin_profile',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('magasin', 'Magasin'), ('employer', 'Employer')], default='employer', max_length=20),
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='PlatformRequest',
        ),
        migrations.DeleteModel(
            name='SubscriptionOffer',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
