# Generated by Django 6.0.4 on 2026-09-06 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_remove_platformrequest_device_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaisseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caisse_categories', to='users.adminprofile')),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépense',
                'ordering': ['nom'],
                'unique_together': {('admin_profile', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='caissemovement',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='users.caissecategory'),
        ),
    ]
