# Generated by Django 6.0.4 on 2026-09-08 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_caissecategory_caissemovement_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
