# Generated by Django 6.0.4 on 2026-09-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_chatmessage_image_alter_chatmessage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='caissemovement',
            name='origine',
            field=models.CharField(choices=[('MANUEL', 'Saisie manuelle'), ('VENTE', 'Vente'), ('PAIEMENT_CLIENT', 'Paiement client'), ('AUTRE_ENTREE', 'Autre entrée'), ('ACHAT_STOCK', 'Achat stock'), ('BOOST', 'Boost / publicité'), ('RETRAIT', 'Retrait'), ('DEPENSE', 'Dépense'), ('FRAIS_LIVRAISON', 'Frais de livraison'), ('ANNULATION_VENTE', 'Annulation / remboursement de vente'), ('AUTRE_SORTIE', 'Autre sortie')], default='MANUEL', max_length=20),
        ),
        migrations.AddField(
            model_name='caissemovement',
            name='reference',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
