# Generated by Django 6.0.4 on 2026-09-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_caissemovement_origine_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caissemovement',
            name='origine',
            field=models.CharField(choices=[('MANUEL', 'Saisie manuelle'), ('VENTE', 'Vente'), ('PAIEMENT_CLIENT', 'Paiement client'), ('AUTRE_ENTREE', 'Autre entrée'), ('ACHAT_STOCK', 'Achat stock'), ('BOOST', 'Boost / publicité'), ('RETRAIT', 'Retrait'), ('DEPENSE', 'Dépense'), ('FRAIS_LIVRAISON', 'Frais de livraison'), ('AVANCE_LIVREUR', 'Avance déjà reçue du livreur'), ('ANNULATION_VENTE', 'Annulation / remboursement de vente'), ('AUTRE_SORTIE', 'Autre sortie')], default='MANUEL', max_length=20),
        ),
    ]
