# Generated by Django 6.0.4 on 2026-10-07 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_origine_avance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magasinprofile',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'magasin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magasin_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
