# Generated by Django 6.0.4 on 2026-10-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_magasinprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='magasinprofile',
            name='adresse',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='magasinprofile',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='magasinprofile',
            name='telephone_2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
