# Generated by Django 6.0.4 on 2026-09-03 06:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0020_remove_notification_movement_remove_product_magasin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('COMMANDE', 'Commandé'), ('RECU', 'Reçu')], default='BROUILLON', max_length=20)),
                ('prix_fournisseur', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fret_import', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('douane', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('meta_ads', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_qty', models.PositiveIntegerField(default=0, editable=False)),
                ('cout_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('cout_unitaire', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_orders', to=settings.AUTH_USER_MODEL)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_orders', to='users.magasinprofile')),
            ],
            options={
                'verbose_name': 'Commande fournisseur',
                'verbose_name_plural': 'Commandes fournisseur',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('cout_unitaire_calcule', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('total_ligne', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_order_lines', to='catalog.productvariant')),
                ('supplier_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='suppliers.supplierorder')),
            ],
            options={
                'verbose_name': 'Ligne de commande fournisseur',
                'verbose_name_plural': 'Lignes de commande fournisseur',
            },
        ),
    ]
