# Generated by Django 6.0.4 on 2026-09-07 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplierorder',
            name='meta_ads',
        ),
    ]
