# Generated by Django 6.0.4 on 2026-09-13 11:17

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productnote'),
        ('suppliers', '0002_remove_supplierorder_meta_ads'),
        ('users', '0025_chatmessage_image_alter_chatmessage_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplierorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Approvisionnement fournisseur', 'verbose_name_plural': 'Approvisionnements fournisseur'},
        ),
        migrations.AlterModelOptions(
            name='supplierorderline',
            options={'verbose_name': "Ligne d'approvisionnement", 'verbose_name_plural': "Lignes d'approvisionnement"},
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='date_arrivee',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='date_expedition',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='destination',
            field=models.CharField(blank=True, default='Madagascar', max_length=150),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='devise',
            field=models.CharField(choices=[('MGA', 'Ariary (MGA)'), ('USD', 'Dollar US (USD)'), ('EUR', 'Euro (EUR)'), ('CNY', 'Yuan (CNY)')], default='MGA', max_length=3),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='finalise_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='lieu_depart',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='methode_allocation',
            field=models.CharField(choices=[('VALEUR', "Proportionnelle à la valeur d'achat"), ('QUANTITE', 'Proportionnelle à la quantité'), ('MANUEL', 'Manuelle (par ligne)')], default='VALEUR', max_length=10),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='mode_transport',
            field=models.CharField(blank=True, choices=[('AERIEN', 'Aérien'), ('MARITIME', 'Maritime'), ('ROUTIER', 'Routier'), ('EXPRESS', 'Express / colis'), ('AUTRE', 'Autre')], max_length=10),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='taux_change',
            field=models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=14),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='total_frais_mga',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='tracking',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='transporteur',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='valeur_achat_mga',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16),
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='allocation_manuelle_mga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='frais_alloues_mga',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16),
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='quantite_recue',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='valeur_achat_mga',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='cout_total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16),
        ),
        migrations.AlterField(
            model_name='supplierorder',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('COMMANDE', 'Commandé'), ('PARTIELLEMENT_PAYE', 'Partiellement payé'), ('PAYE', 'Payé'), ('PREPARE', 'Préparé par le fournisseur'), ('EN_TRANSIT', 'En transit'), ('ARRIVE', 'Arrivé à Madagascar'), ('PARTIELLEMENT_RECU', 'Partiellement réceptionné'), ('RECU', 'Réceptionné'), ('COUT_FINALISE', 'Coût finalisé')], default='BROUILLON', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplierorderline',
            name='total_ligne',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('pays', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(blank=True, max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('devise', models.CharField(choices=[('MGA', 'Ariary (MGA)'), ('USD', 'Dollar US (USD)'), ('EUR', 'Euro (EUR)'), ('CNY', 'Yuan (CNY)')], default='USD', max_length=3)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='users.adminprofile')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='supplierorder',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='suppliers.supplier'),
        ),
        migrations.CreateModel(
            name='SupplierFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=16)),
                ('devise', models.CharField(choices=[('MGA', 'Ariary (MGA)'), ('USD', 'Dollar US (USD)'), ('EUR', 'Euro (EUR)'), ('CNY', 'Yuan (CNY)')], default='MGA', max_length=3)),
                ('taux_change', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=14)),
                ('montant_mga', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('type_frais', models.CharField(choices=[('TRANSPORT', 'Transport / expédition'), ('DOUANE', 'Douane'), ('TAXES', 'Taxes'), ('TRANSIT', 'Frais de transit'), ('TRANSPORT_LOCAL', 'Transport local'), ('PORTUAIRE', 'Frais portuaires'), ('DOSSIER', 'Frais de dossier'), ('AGENCE', "Frais d'agence"), ('ASSURANCE', 'Assurance'), ('MANUTENTION', 'Manutention'), ('AUTRE', 'Autres frais')], default='AUTRE', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('prestataire', models.CharField(blank=True, max_length=150)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='supplier_fees/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_fees', to=settings.AUTH_USER_MODEL)),
                ('supplier_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='suppliers.supplierorder')),
            ],
            options={
                'verbose_name': "Frais d'importation",
                'verbose_name_plural': "Frais d'importation",
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=16)),
                ('devise', models.CharField(choices=[('MGA', 'Ariary (MGA)'), ('USD', 'Dollar US (USD)'), ('EUR', 'Euro (EUR)'), ('CNY', 'Yuan (CNY)')], default='MGA', max_length=3)),
                ('taux_change', models.DecimalField(decimal_places=4, default=Decimal('1'), max_digits=14)),
                ('montant_mga', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('type_paiement', models.CharField(choices=[('ACOMPTE', 'Acompte'), ('SOLDE', 'Solde'), ('PARTIEL', 'Paiement partiel'), ('AUTRE', 'Autre')], default='ACOMPTE', max_length=10)),
                ('methode', models.CharField(choices=[('VIREMENT', 'Virement bancaire'), ('MOBILE_MONEY', 'Mobile money'), ('ESPECES', 'Espèces'), ('CARTE', 'Carte'), ('AUTRE', 'Autre')], default='VIREMENT', max_length=15)),
                ('reference', models.CharField(blank=True, max_length=150)),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='supplier_payments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payments', to=settings.AUTH_USER_MODEL)),
                ('supplier_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='suppliers.supplierorder')),
            ],
            options={
                'verbose_name': 'Paiement fournisseur',
                'verbose_name_plural': 'Paiements fournisseur',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VariantCostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('valeur_achat_unitaire_mga', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('frais_unitaire_mga', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cout_revient_unitaire_mga', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_history', to='catalog.productvariant')),
                ('supplier_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_history', to='suppliers.supplierorder')),
            ],
            options={
                'verbose_name': 'Historique de coût de revient',
                'verbose_name_plural': 'Historique des coûts de revient',
                'ordering': ['-date', '-id'],
                'unique_together': {('product_variant', 'supplier_order')},
            },
        ),
    ]
