# Generated by Django 6.0.4 on 2026-09-12 13:58

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0015_finance_fields'),
        ('users', '0026_caissemovement_origine_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encaissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('LIVREUR', 'Encaissé par le livreur'), ('COMPTOIR', 'Encaissé au comptoir'), ('PREPAYE', "Payé d'avance")], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('REMIS', 'Remis en caisse'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=12)),
                ('remis_le', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caisse_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encaissement', to='users.caissemovement')),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encaissements', to=settings.AUTH_USER_MODEL)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encaissements', to='users.magasinprofile')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encaissement', to='orders.order')),
                ('remis_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remises_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Encaissement',
                'verbose_name_plural': 'Encaissements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EpargneMouvement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('VERSEMENT', 'Versement automatique'), ('RETRAIT', 'Retrait'), ('CORRECTION', 'Correction')], max_length=12)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('solde_apres', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epargne_mouvements', to=settings.AUTH_USER_MODEL)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epargne_mouvements', to='users.magasinprofile')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='epargne_mouvements', to='orders.order')),
            ],
            options={
                'verbose_name': "Mouvement d'épargne",
                'verbose_name_plural': "Mouvements d'épargne",
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pct_reappro', models.DecimalField(decimal_places=2, default=Decimal('60'), max_digits=5)),
                ('pct_epargne', models.DecimalField(decimal_places=2, default=Decimal('25'), max_digits=5)),
                ('pct_depenses', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finance_settings', to='users.adminprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètres financiers',
                'verbose_name_plural': 'Paramètres financiers',
            },
        ),
        migrations.CreateModel(
            name='VenteResultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vente', models.DateField()),
                ('nb_articles', models.PositiveIntegerField(default=0)),
                ('ca_produits', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('livraison_client', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('cout_achat', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('frais_agence', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('part_boost', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('gain_reel', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('pct_reappro', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('pct_epargne', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('pct_depenses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('part_reappro', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('part_epargne', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('part_depenses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('annule', models.BooleanField(default=False)),
                ('epargne_active', models.BooleanField(default=True)),
                ('calcule_le', models.DateTimeField(default=django.utils.timezone.now)),
                ('maj_le', models.DateTimeField(auto_now=True)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes_resultats', to='users.magasinprofile')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat', to='orders.order')),
            ],
            options={
                'verbose_name': 'Résultat de vente',
                'verbose_name_plural': 'Résultats de vente',
                'ordering': ['-date_vente', '-id'],
            },
        ),
    ]
