# Generated by Django 5.2.17 on 2026-09-02 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_order_lines', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='supplierorderline',
            name='supplier_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='suppliers.supplierorder'),
        ),
    ]
