# Generated by Django 6.0.4 on 2026-09-28 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('orders', '0021_remove_order_client_order_origine_en_ligne'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
