# Generated by Django 6.0.4 on 2026-09-03 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0020_remove_notification_movement_remove_product_magasin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='users.magasinprofile')),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
                'ordering': ['nom'],
                'unique_together': {('magasin', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='users.magasinprofile')),
            ],
            options={
                'verbose_name': 'Catégorie de produit',
                'verbose_name_plural': 'Catégories de produit',
                'ordering': ['ordre', 'nom'],
                'unique_together': {('magasin', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='catalog.productcategory')),
            ],
            options={
                'verbose_name': 'Sous-type de produit',
                'verbose_name_plural': 'Sous-types de produit',
                'ordering': ['category', 'nom'],
                'unique_together': {('category', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='ProductReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_name', models.CharField(max_length=150)),
                ('prix_vente', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='catalog.brand')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='catalog.producttype')),
            ],
            options={
                'verbose_name': 'Référence produit',
                'verbose_name_plural': 'Références produit',
                'ordering': ['brand', 'reference_name'],
                'unique_together': {('type', 'brand', 'reference_name')},
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couleur', models.CharField(default='Standard', max_length=100)),
                ('sku_loyverse', models.CharField(blank=True, max_length=30, null=True)),
                ('stock_actuel', models.IntegerField(default=0)),
                ('seuil_alerte', models.IntegerField(default=1)),
                ('product_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.productreference')),
            ],
            options={
                'verbose_name': 'Variante de produit',
                'verbose_name_plural': 'Variantes de produit',
                'ordering': ['product_reference', 'couleur'],
                'unique_together': {('product_reference', 'couleur')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10)),
                ('quantite', models.PositiveIntegerField()),
                ('origine', models.CharField(choices=[('LIVRE', 'Commande livrée'), ('FOURNISSEUR', 'Réception fournisseur'), ('AJUSTEMENT', 'Ajustement manuel')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='catalog.productvariant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-timestamp'],
            },
        ),
    ]
