# Generated by Django 6.0.4 on 2026-09-04 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0020_remove_notification_movement_remove_product_magasin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreference',
            name='prix_achat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='users.magasinprofile')),
            ],
            options={
                'verbose_name': 'Couleur',
                'verbose_name_plural': 'Couleurs',
                'ordering': ['nom'],
                'unique_together': {('magasin', 'nom')},
            },
        ),
    ]
