# Generated by Django 6.0.4 on 2026-09-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productreference_prix_achat_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreference',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
