# Generated by Django 6.0.4 on 2026-09-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productreference_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='origine',
            field=models.CharField(choices=[('PREPARATION', 'Préparation de commande'), ('RETOUR', 'Retour de commande'), ('FOURNISSEUR', 'Réception fournisseur'), ('AJUSTEMENT', 'Ajustement manuel')], max_length=20),
        ),
    ]
