# Generated by Django 6.0.4 on 2026-09-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_stockmovement_origine'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='avec_couleurs',
            field=models.BooleanField(default=True),
        ),
    ]
