# Generated by Django 6.0.4 on 2026-09-08 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_productcategory_avec_couleurs'),
        ('users', '0024_chatmessage_read_at_customuser_last_seen_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('items', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='users.magasinprofile')),
            ],
            options={
                'verbose_name': 'Import de catalogue',
                'verbose_name_plural': 'Imports de catalogue',
                'ordering': ['-created_at'],
            },
        ),
    ]
