# Generated by Django 6.0.4 on 2026-09-12 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_productnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='origine',
            field=models.CharField(choices=[('COMMANDE', 'Création de commande'), ('PREPARATION', 'Préparation de commande'), ('RETOUR', 'Retour de commande'), ('ANNULATION', 'Annulation de commande'), ('FOURNISSEUR', 'Réception fournisseur'), ('AJUSTEMENT', 'Ajustement manuel')], max_length=20),
        ),
    ]
