# Generated by Django 6.0.4 on 2026-09-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_stockmovement_origine_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='visible_client',
            field=models.BooleanField(default=True, verbose_name='Afficher sur le site de vente'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='visible_client',
            field=models.BooleanField(default=True, verbose_name='Afficher sur le site de vente'),
        ),
    ]
