# Generated by Django 5.2.17 on 2026-09-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='origine',
            field=models.CharField(choices=[('LIVRE', 'Commande livrée'), ('FOURNISSEUR', 'Réception fournisseur'), ('AJUSTEMENT', 'Ajustement manuel')], max_length=20),
        ),
    ]
