# Generated by Django 6.0.4 on 2026-09-03 06:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('users', '0020_remove_notification_movement_remove_product_magasin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=30, unique=True)),
                ('date_commande', models.DateField(default=django.utils.timezone.localdate)),
                ('client_nom', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('livraison_zone', models.CharField(choices=[('ZONE1', 'Zone 1'), ('ZONE2', 'Zone 2'), ('ZONE3', 'Zone 3'), ('RECUPERATION', 'Récupération')], max_length=20)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('total_a_payer', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('note', models.TextField(blank=True, null=True)),
                ('statut_courant', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête'), ('EN_LIVRAISON', 'En livraison'), ('LIVRE', 'Livré'), ('RETOUR', 'Retour')], default='NOUVELLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.magasinprofile')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='catalog.productvariant')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, choices=[('NOUVELLE', 'Nouvelle'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête'), ('EN_LIVRAISON', 'En livraison'), ('LIVRE', 'Livré'), ('RETOUR', 'Retour')], max_length=20, null=True)),
                ('nouveau_statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête'), ('EN_LIVRAISON', 'En livraison'), ('LIVRE', 'Livré'), ('RETOUR', 'Retour')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'Historique statut commande',
                'verbose_name_plural': 'Historiques statut commande',
                'ordering': ['timestamp'],
            },
        ),
    ]
