# Generated by Django 6.0.4 on 2026-09-03 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adresse_livraison',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_commande',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
