# Generated by Django 6.0.4 on 2026-09-07 10:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_livreur_order_preparateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatushistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
