# Generated by Django 6.0.4 on 2026-09-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderstatushistory_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='statut_courant',
            field=models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête'), ('EN_LIVRAISON', 'En livraison'), ('LIVRE', 'Livré'), ('RETOUR', 'Retour'), ('ANNULEE', 'Annulée')], default='NOUVELLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='ancien_statut',
            field=models.CharField(blank=True, choices=[('NOUVELLE', 'Nouvelle'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête'), ('EN_LIVRAISON', 'En livraison'), ('LIVRE', 'Livré'), ('RETOUR', 'Retour'), ('ANNULEE', 'Annulée')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='nouveau_statut',
            field=models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête'), ('EN_LIVRAISON', 'En livraison'), ('LIVRE', 'Livré'), ('RETOUR', 'Retour'), ('ANNULEE', 'Annulée')], max_length=20),
        ),
    ]
