# Generated by Django 6.0.4 on 2026-09-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_statut_courant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mode_paiement',
            field=models.CharField(choices=[('AVANT', 'Paiement avant la livraison'), ('LIVRAISON', 'Paiement à la livraison')], default='LIVRAISON', max_length=20),
        ),
    ]
