# Generated by Django 6.0.4 on 2026-09-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_mode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatushistory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='order_status_photos/'),
        ),
    ]
