# Generated by Django 6.0.4 on 2026-09-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderstatushistory_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='note',
        ),
        migrations.AddField(
            model_name='order',
            name='note_livreur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='note_preparateur',
            field=models.TextField(blank=True, null=True),
        ),
    ]
