# Generated by Django 6.0.4 on 2026-09-09 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_note_order_note_livreur_and_more'),
        ('users', '0024_chatmessage_read_at_customuser_last_seen_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='livraison_zone',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryZoneOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=20)),
                ('nom', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_zones', to='users.adminprofile')),
            ],
            options={
                'verbose_name': 'Zone de livraison',
                'verbose_name_plural': 'Zones de livraison',
                'ordering': ['prix', 'nom'],
                'unique_together': {('admin_profile', 'code')},
            },
        ),
    ]
