# Generated by Django 6.0.4 on 2026-09-09 16:15
#
# Seed additif uniquement : crée les 3 zones historiques (ZONE1/2/3, tarifs
# jusqu'ici codés en dur dans Order.FRAIS_PAR_ZONE) pour chaque société déjà
# existante, avec le même `code` que les commandes existantes utilisent déjà
# dans Order.livraison_zone — pour que celles-ci continuent de résoudre leur
# frais de livraison correctement une fois la table dynamique DeliveryZoneOption
# en place (§ demande — CRUD zones dans Paramètres). Ne modifie ni ne
# supprime aucune commande ni aucun autre enregistrement existant : safe à
# rejouer (get_or_create) et safe sur une base de production (VPS).

from django.db import migrations

LEGACY_ZONES = [
    ("ZONE1", "Zone 1", 3000),
    ("ZONE2", "Zone 2", 4000),
    ("ZONE3", "Zone 3", 5000),
]


def seed_legacy_zones(apps, schema_editor):
    AdminProfile = apps.get_model("users", "AdminProfile")
    DeliveryZoneOption = apps.get_model("orders", "DeliveryZoneOption")

    for admin_profile in AdminProfile.objects.all():
        for code, nom, prix in LEGACY_ZONES:
            DeliveryZoneOption.objects.get_or_create(
                admin_profile=admin_profile, code=code, defaults={"nom": nom, "prix": prix},
            )


def noop_reverse(apps, schema_editor):
    # Volontairement un no-op : supprimer ces lignes au downgrade casserait
    # la résolution des frais pour toute commande existante qui référence
    # encore ZONE1/2/3 (voir Order.save()).
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_livraison_zone_deliveryzoneoption'),
    ]

    operations = [
        migrations.RunPython(seed_legacy_zones, noop_reverse),
    ]
