# Generated by Django 6.0.4 on 2026-09-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_seed_legacy_delivery_zones'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='retourne',
            field=models.BooleanField(default=False),
        ),
    ]
