# Generated by Django 6.0.4 on 2026-09-11 15:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderitem_retourne'),
        ('users', '0025_chatmessage_image_alter_chatmessage_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('par_unite', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_types', to='users.adminprofile')),
            ],
            options={
                'verbose_name': 'Type de dépense',
                'verbose_name_plural': 'Types de dépense',
                'ordering': ['nom'],
                'unique_together': {('admin_profile', 'nom')},
            },
        ),
        migrations.CreateModel(
            name='LivreurExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('montant', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('motif', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTE', 'Acceptée'), ('REJETE', 'Rejetée')], default='EN_ATTENTE', max_length=12)),
                ('motif_rejet', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livreur_expenses', to='users.magasinprofile')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_expenses', to=settings.AUTH_USER_MODEL)),
                ('type_depense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='orders.expensetype')),
            ],
            options={
                'verbose_name': 'Dépense livreur',
                'verbose_name_plural': 'Dépenses livreur',
                'ordering': ['-created_at'],
            },
        ),
    ]
