# Generated by Django 6.0.4 on 2026-09-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_expensetype_livreurexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='telephone_2',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
