# Generated by Django 6.0.4 on 2026-09-12 12:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_telephone_2'),
        ('users', '0025_chatmessage_image_alter_chatmessage_content'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('plateforme', models.CharField(choices=[('FACEBOOK', 'Facebook'), ('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('GOOGLE', 'Google'), ('AUTRE', 'Autre')], default='FACEBOOK', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_debut', models.DateField(default=django.utils.timezone.localdate)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_campaigns', to='users.magasinprofile')),
            ],
            options={
                'verbose_name': 'Campagne marketing',
                'verbose_name_plural': 'Campagnes marketing',
                'ordering': ['-date_debut', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='campagne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.marketingcampaign'),
        ),
    ]
