# Generated by Django 6.0.4 on 2026-09-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_marketingcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='prix_catalogue',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
    ]
