# Generated by Django 6.0.4 on 2026-09-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_marketingcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryzoneoption',
            name='cout_agence',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='type_periode',
            field=models.CharField(choices=[('JOUR', 'Jour'), ('SEMAINE', 'Semaine'), ('MOIS', 'Mois'), ('PERSONNALISE', 'Personnalisée')], default='PERSONNALISE', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='frais_agence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
