# Generated by Django 6.0.4 on 2026-09-13 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('orders', '0015_orderitem_prix_catalogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='statut_courant',
            field=models.CharField(choices=[('EN_ATTENTE_APPROBATION', "En attente d'approbation"), ('NOUVELLE', 'Nouvelle'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête'), ('EN_LIVRAISON', 'En livraison'), ('LIVRE', 'Livré'), ('RETOUR', 'Retour'), ('ANNULEE', 'Annulée')], default='NOUVELLE', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='ancien_statut',
            field=models.CharField(blank=True, choices=[('EN_ATTENTE_APPROBATION', "En attente d'approbation"), ('NOUVELLE', 'Nouvelle'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête'), ('EN_LIVRAISON', 'En livraison'), ('LIVRE', 'Livré'), ('RETOUR', 'Retour'), ('ANNULEE', 'Annulée')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='nouveau_statut',
            field=models.CharField(choices=[('EN_ATTENTE_APPROBATION', "En attente d'approbation"), ('NOUVELLE', 'Nouvelle'), ('EN_PREPARATION', 'En préparation'), ('PRETE', 'Prête'), ('EN_LIVRAISON', 'En livraison'), ('LIVRE', 'Livré'), ('RETOUR', 'Retour'), ('ANNULEE', 'Annulée')], max_length=30),
        ),
    ]
