# Generated by Django 6.0.4 on 2026-09-13 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_order_client_alter_order_statut_courant_and_more'),
        ('orders', '0016_reserver_stock_commandes_nouvelles'),
    ]

    operations = [
    ]
