# Generated by Django 6.0.4 on 2026-09-16 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('orders', '0017_merge_20260913_1723'),
        ('users', '0026_caissemovement_origine_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='marketingcampaign',
            index=models.Index(fields=['magasin', 'date_debut', 'date_fin'], name='orders_campaign_periode_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['magasin', 'date_commande'], name='orders_order_mag_date_idx'),
        ),
    ]
