# Generated by Django 6.0.4 on 2026-09-16 08:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_merge_20260913_1723'),
        ('users', '0026_caissemovement_origine_reference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvanceLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moyen', models.CharField(choices=[('MVOLA', 'Mvola'), ('ORANGE_MONEY', 'Orange Money'), ('AIRTEL_MONEY', 'Airtel Money'), ('ESPECES', 'Espèces'), ('VIREMENT', 'Virement bancaire'), ('AUTRE', 'Autre')], default='MVOLA', max_length=15)),
                ('reference_transfert', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmée'), ('REJETE', 'Rejetée')], default='EN_ATTENTE', max_length=12)),
                ('motif_rejet', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('livreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances', to=settings.AUTH_USER_MODEL)),
                ('magasin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances_livreur', to='users.magasinprofile')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_avances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avance du livreur',
                'verbose_name_plural': 'Avances des livreurs',
                'ordering': ['-created_at'],
            },
        ),
    ]
