# Generated by Django 6.0.4 on 2026-09-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_avance_livreur'),
        ('orders', '0019_expensetype_frais_livraison'),
    ]

    operations = [
    ]
